// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0mfF6JPjoxY3T2lCpWuqviZcaSuMp6IY',
    appId: '1:1097337180967:web:f5d3e977c08fe64c414f02',
    messagingSenderId: '1097337180967',
    projectId: 'collectorhub-79121',
    authDomain: 'collectorhub-79121.firebaseapp.com',
    storageBucket: 'collectorhub-79121.firebasestorage.app',
    measurementId: 'G-PB9TG71HEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALxi5bI3oIHXZmwLs0vuakGsKyfnCgVEc',
    appId: '1:1097337180967:android:ce8cf4d5c0cd452f414f02',
    messagingSenderId: '1097337180967',
    projectId: 'collectorhub-79121',
    storageBucket: 'collectorhub-79121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCacE9g-K9xBhiTPi9W2a-7KPYoDYt32Cg',
    appId: '1:1097337180967:ios:bc90253f0e7e0dcb414f02',
    messagingSenderId: '1097337180967',
    projectId: 'collectorhub-79121',
    storageBucket: 'collectorhub-79121.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCacE9g-K9xBhiTPi9W2a-7KPYoDYt32Cg',
    appId: '1:1097337180967:ios:bc90253f0e7e0dcb414f02',
    messagingSenderId: '1097337180967',
    projectId: 'collectorhub-79121',
    storageBucket: 'collectorhub-79121.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0mfF6JPjoxY3T2lCpWuqviZcaSuMp6IY',
    appId: '1:1097337180967:web:8fa40dcebe453620414f02',
    messagingSenderId: '1097337180967',
    projectId: 'collectorhub-79121',
    authDomain: 'collectorhub-79121.firebaseapp.com',
    storageBucket: 'collectorhub-79121.firebasestorage.app',
    measurementId: 'G-NKMPN81GS8',
  );

}